---
- hosts: all
  tasks:
   - name: create a partition
     yum: 
       name: mariadb-server
       state: latest
     loop: "{{ansible_mounts}}"
     when: item.count == "/" and item.size_available < "12323942423423"