---
- hosts: all
  tasks:
   - name: create a partition
     parted:
       device: /dev/nvme0n1
       number: 2
       state: present
       part_end: 10MiB
     when: ansible_devices.xvda.size <= "8.00 GB"
     