---
- hosts: prodserver
  tasks:
   - yum:
       name: httpd
       state: present
   - file:
      path: /var/www/webserver
      state: directory
       
   - copy:
       src: index.html
       dest: /var/www/webserver
       
   - copy:
        src: 1.conf
        dest: /etc/httpd/conf.d/1.conf
     notify: restart_service
        
   - service:
       name: httpd
       state: started
  handlers:
   - name: restart_service
     service:
       name: httpd
       state: restarted