---
- hosts: all
  tasks: 
   - name: add a group
     group:
       name: cycle
   - name: add a user
     user:
      name: "{{item.name}}"
      group: "{{item.group}}"
     loop:
       - name: ramesh
         group: wheel
       - name: shyam
         group: cycle