---
- name: This playbook performs multipile activites
  hosts: dbserver
  tasks:
    - package:
         name: ntpdate
         state: present
    - copy:
        src: /srv/myfiles/foo.conf
        state: touch
        dest: /etc/foo.conf
        owner: foo
        group: foo
        mode: '0644'
  
    - service:
	    name: crond
        state: started
    - firewalld:
        port: 8081/tcp
    	permanent: yes
        state: disabled
