---
# configuring web server
- hosts: dbserver
  tasks:
    - yum:
         name: httpd
         state: latest
    - copy:
         content: "This is my first web site"
         dest: /var/www/html/index.html
         
    - service:
         name: httpd
         status: started
         enabled: yes
         
 # checking if it is working fine or not.
 
- hosts: dbserver
  tasks:
    - uri:
         url:  http://managednode1
         return_content: yes
         status_code: 200