---
- name: This playbook performs multipile activites
  hosts: dbserver
  tasks:
    - package:
         name: ntpdate
         state: present
    - firewalld:
         port: 8081/tcp
    	 permanent: yes
         state: disabled