---
- hosts: dbserver
  tasks:
    - name: install a package
      yum:
        name: "{{package_name}}"
        state: present
    - name: start the service
      service:
        name: "{{package_name}}"
        state: started
        

# ansible-playbook var1.yaml -e package_name=nginx      >> you need to provide package name during command execution.