---
- name: Install a package
  yum:
   name: "{{package_name}}"
   state: present
   
- name: copy a file to managed server
  ansible.builtin.copy:
   src: index.html
   dest: "{{documentroot}}"
  ignore_errors: yes
   
- name: start the service
  service:
   name: "{{service_name}}"
   state: "{{state}}"

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: http://localhost:80
   
   
























# tasks file for apache_project