---
- name: Install a package
  yum:
   name: "{{package_name}}"
   state: present
   
- name: copy a file to managed server
  ansible.builtin.copy:
   src: index.html
   dest: "{{documentroot}}"
  ignore_errors: yes
   
- name: start the service
  service:
   name: "{{service_name}}"
   state: "{{state}}"

   
   
























# tasks file for apache_project