---
- hosts: all
  tasks:
   - name: copy a file
     copy:
       src: users.sh
       dest: /usr/user.sh
       mode: '0777'
   - name: print something
     shell: /usr/users.sh
     register: output
     failed_when: output.changed == "true"
   - debug:
      var: output