---
- name: This playbook performs multipile activites
  hosts: dbserver
  tasks:
    - package:
         name: ntpdate
         state: present
         
    - firewalld:
         service: https
         permanent: true
         state: enabled