---
- hosts: prodserver
  tasks:
   - name: install httpd
     service: 
       name: httpd
       state: restarted
     register: service_output
     
   - debug: var=service_output
   
   - name: print a msg
     debug :
       msg : service is active
     when: service_output.status.ActiveState == "inactive"